default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  username: admin
  password: Yukky1riraa*
  host: database-1.c9dxrrdszjr1.ap-northeast-1.rds.amazonaws.com
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: runteq_production
